version: '3'
services:
  api-gateway:
    build: ../backend/api-gateway
    ports:
      - "10012:8080"
    depends_on:
      - config
    networks: 
      - backend
  config:
    build: ../backend/config
    ports:
      - "10180:8080"
    networks: 
      - backend
  user-service:
    build: ../backend/user-service
    links:
      - api-gateway
    depends_on:
      - config
      - mongodb
    ports:
      - "10017:8080"
    networks: 
      - backend
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    networks: 
     - backend
    command: mongod --smallfiles --logpath=/dev/null # --quiet
networks:
  backend:
    driver: "bridge"