spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/esm
  profiles:
    active: native
---
#if you want to gather all the configs yml files from local folder
spring:
  profiles: prod
  cloud:
    config:
      server:
        git:
          uri: file:///opt/config
